apiVersion: v1
kind: Service
metadata:
  name: {{ include "worknest.fullname" . }}
  labels: {{- include "worknest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.worknest.service.type }}
  ports:
    - port: {{ .Values.worknest.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "worknest.selectorLabels" . | nindent 4 }}