{{- if .Values.worknest.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "worknest.serviceAccountName" . }}
  labels:
    {{- include "worknest.labels" . | nindent 4 }}
  {{- with .Values.worknest.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.worknest.serviceAccount.automount }}
{{- end }}
