/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppOrgsRouteImport } from './routes/_app/orgs'
import { Route as AuthInviteTokenRouteImport } from './routes/_auth/invite.$token'
import { Route as AppOrgSlugWsSlugRouteImport } from './routes/_app/$orgSlug/$wsSlug'
import { Route as AppOrgSlugWsSlugIndexRouteImport } from './routes/_app/$orgSlug/$wsSlug/index'
import { Route as AppOrgSlugWsSlugWikiIndexRouteImport } from './routes/_app/$orgSlug/$wsSlug/wiki/index'
import { Route as AppOrgSlugWsSlugSettingsIndexRouteImport } from './routes/_app/$orgSlug/$wsSlug/settings/index'
import { Route as AppOrgSlugWsSlugProjectsIndexRouteImport } from './routes/_app/$orgSlug/$wsSlug/projects/index'
import { Route as AppOrgSlugWsSlugWikiSpaceIdRouteImport } from './routes/_app/$orgSlug/$wsSlug/wiki/$spaceId'
import { Route as AppOrgSlugWsSlugSettingsProfileRouteImport } from './routes/_app/$orgSlug/$wsSlug/settings/profile'
import { Route as AppOrgSlugWsSlugSettingsMembersRouteImport } from './routes/_app/$orgSlug/$wsSlug/settings/members'
import { Route as AppOrgSlugWsSlugProjectsProjectIdRouteImport } from './routes/_app/$orgSlug/$wsSlug/projects/$projectId'
import { Route as AppOrgSlugWsSlugMyIssuesRouteImport } from './routes/_app/$orgSlug/$wsSlug/my/issues'
import { Route as AppOrgSlugWsSlugMyInboxRouteImport } from './routes/_app/$orgSlug/$wsSlug/my/inbox'
import { Route as AppOrgSlugWsSlugMyFavoritesRouteImport } from './routes/_app/$orgSlug/$wsSlug/my/favorites'
import { Route as AppOrgSlugWsSlugSettingsOrgIndexRouteImport } from './routes/_app/$orgSlug/$wsSlug/settings/org/index'
import { Route as AppOrgSlugWsSlugWikiSpaceIdPageIdRouteImport } from './routes/_app/$orgSlug/$wsSlug/wiki/$spaceId/$pageId'
import { Route as AppOrgSlugWsSlugSettingsOrgMembersRouteImport } from './routes/_app/$orgSlug/$wsSlug/settings/org/members'
import { Route as AppOrgSlugWsSlugProjectsProjectIdWikiIndexRouteImport } from './routes/_app/$orgSlug/$wsSlug/projects/$projectId/wiki/index'
import { Route as AppOrgSlugWsSlugProjectsProjectIdSettingsIndexRouteImport } from './routes/_app/$orgSlug/$wsSlug/projects/$projectId/settings/index'
import { Route as AppOrgSlugWsSlugProjectsProjectIdIssuesIndexRouteImport } from './routes/_app/$orgSlug/$wsSlug/projects/$projectId/issues/index'
import { Route as AppOrgSlugWsSlugProjectsProjectIdGanttIndexRouteImport } from './routes/_app/$orgSlug/$wsSlug/projects/$projectId/gantt/index'
import { Route as AppOrgSlugWsSlugProjectsProjectIdCyclesIndexRouteImport } from './routes/_app/$orgSlug/$wsSlug/projects/$projectId/cycles/index'
import { Route as AppOrgSlugWsSlugProjectsProjectIdBoardIndexRouteImport } from './routes/_app/$orgSlug/$wsSlug/projects/$projectId/board/index'
import { Route as AppOrgSlugWsSlugProjectsProjectIdViewsViewIdRouteImport } from './routes/_app/$orgSlug/$wsSlug/projects/$projectId/views/$viewId'
import { Route as AppOrgSlugWsSlugProjectsProjectIdSettingsMembersRouteImport } from './routes/_app/$orgSlug/$wsSlug/projects/$projectId/settings/members'
import { Route as AppOrgSlugWsSlugProjectsProjectIdSettingsLabelsRouteImport } from './routes/_app/$orgSlug/$wsSlug/projects/$projectId/settings/labels'
import { Route as AppOrgSlugWsSlugProjectsProjectIdIssuesIssueIdRouteImport } from './routes/_app/$orgSlug/$wsSlug/projects/$projectId/issues/$issueId'
import { Route as AppOrgSlugWsSlugProjectsProjectIdCyclesCycleIdRouteImport } from './routes/_app/$orgSlug/$wsSlug/projects/$projectId/cycles/$cycleId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppOrgsRoute = AppOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AppRoute,
} as any)
const AuthInviteTokenRoute = AuthInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AuthRoute,
} as any)
const AppOrgSlugWsSlugRoute = AppOrgSlugWsSlugRouteImport.update({
  id: '/$orgSlug/$wsSlug',
  path: '/$orgSlug/$wsSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgSlugWsSlugIndexRoute = AppOrgSlugWsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSlugWsSlugRoute,
} as any)
const AppOrgSlugWsSlugWikiIndexRoute =
  AppOrgSlugWsSlugWikiIndexRouteImport.update({
    id: '/wiki/',
    path: '/wiki/',
    getParentRoute: () => AppOrgSlugWsSlugRoute,
  } as any)
const AppOrgSlugWsSlugSettingsIndexRoute =
  AppOrgSlugWsSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppOrgSlugWsSlugRoute,
  } as any)
const AppOrgSlugWsSlugProjectsIndexRoute =
  AppOrgSlugWsSlugProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AppOrgSlugWsSlugRoute,
  } as any)
const AppOrgSlugWsSlugWikiSpaceIdRoute =
  AppOrgSlugWsSlugWikiSpaceIdRouteImport.update({
    id: '/wiki/$spaceId',
    path: '/wiki/$spaceId',
    getParentRoute: () => AppOrgSlugWsSlugRoute,
  } as any)
const AppOrgSlugWsSlugSettingsProfileRoute =
  AppOrgSlugWsSlugSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AppOrgSlugWsSlugRoute,
  } as any)
const AppOrgSlugWsSlugSettingsMembersRoute =
  AppOrgSlugWsSlugSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AppOrgSlugWsSlugRoute,
  } as any)
const AppOrgSlugWsSlugProjectsProjectIdRoute =
  AppOrgSlugWsSlugProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppOrgSlugWsSlugRoute,
  } as any)
const AppOrgSlugWsSlugMyIssuesRoute =
  AppOrgSlugWsSlugMyIssuesRouteImport.update({
    id: '/my/issues',
    path: '/my/issues',
    getParentRoute: () => AppOrgSlugWsSlugRoute,
  } as any)
const AppOrgSlugWsSlugMyInboxRoute = AppOrgSlugWsSlugMyInboxRouteImport.update({
  id: '/my/inbox',
  path: '/my/inbox',
  getParentRoute: () => AppOrgSlugWsSlugRoute,
} as any)
const AppOrgSlugWsSlugMyFavoritesRoute =
  AppOrgSlugWsSlugMyFavoritesRouteImport.update({
    id: '/my/favorites',
    path: '/my/favorites',
    getParentRoute: () => AppOrgSlugWsSlugRoute,
  } as any)
const AppOrgSlugWsSlugSettingsOrgIndexRoute =
  AppOrgSlugWsSlugSettingsOrgIndexRouteImport.update({
    id: '/settings/org/',
    path: '/settings/org/',
    getParentRoute: () => AppOrgSlugWsSlugRoute,
  } as any)
const AppOrgSlugWsSlugWikiSpaceIdPageIdRoute =
  AppOrgSlugWsSlugWikiSpaceIdPageIdRouteImport.update({
    id: '/$pageId',
    path: '/$pageId',
    getParentRoute: () => AppOrgSlugWsSlugWikiSpaceIdRoute,
  } as any)
const AppOrgSlugWsSlugSettingsOrgMembersRoute =
  AppOrgSlugWsSlugSettingsOrgMembersRouteImport.update({
    id: '/settings/org/members',
    path: '/settings/org/members',
    getParentRoute: () => AppOrgSlugWsSlugRoute,
  } as any)
const AppOrgSlugWsSlugProjectsProjectIdWikiIndexRoute =
  AppOrgSlugWsSlugProjectsProjectIdWikiIndexRouteImport.update({
    id: '/wiki/',
    path: '/wiki/',
    getParentRoute: () => AppOrgSlugWsSlugProjectsProjectIdRoute,
  } as any)
const AppOrgSlugWsSlugProjectsProjectIdSettingsIndexRoute =
  AppOrgSlugWsSlugProjectsProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppOrgSlugWsSlugProjectsProjectIdRoute,
  } as any)
const AppOrgSlugWsSlugProjectsProjectIdIssuesIndexRoute =
  AppOrgSlugWsSlugProjectsProjectIdIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => AppOrgSlugWsSlugProjectsProjectIdRoute,
  } as any)
const AppOrgSlugWsSlugProjectsProjectIdGanttIndexRoute =
  AppOrgSlugWsSlugProjectsProjectIdGanttIndexRouteImport.update({
    id: '/gantt/',
    path: '/gantt/',
    getParentRoute: () => AppOrgSlugWsSlugProjectsProjectIdRoute,
  } as any)
const AppOrgSlugWsSlugProjectsProjectIdCyclesIndexRoute =
  AppOrgSlugWsSlugProjectsProjectIdCyclesIndexRouteImport.update({
    id: '/cycles/',
    path: '/cycles/',
    getParentRoute: () => AppOrgSlugWsSlugProjectsProjectIdRoute,
  } as any)
const AppOrgSlugWsSlugProjectsProjectIdBoardIndexRoute =
  AppOrgSlugWsSlugProjectsProjectIdBoardIndexRouteImport.update({
    id: '/board/',
    path: '/board/',
    getParentRoute: () => AppOrgSlugWsSlugProjectsProjectIdRoute,
  } as any)
const AppOrgSlugWsSlugProjectsProjectIdViewsViewIdRoute =
  AppOrgSlugWsSlugProjectsProjectIdViewsViewIdRouteImport.update({
    id: '/views/$viewId',
    path: '/views/$viewId',
    getParentRoute: () => AppOrgSlugWsSlugProjectsProjectIdRoute,
  } as any)
const AppOrgSlugWsSlugProjectsProjectIdSettingsMembersRoute =
  AppOrgSlugWsSlugProjectsProjectIdSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AppOrgSlugWsSlugProjectsProjectIdRoute,
  } as any)
const AppOrgSlugWsSlugProjectsProjectIdSettingsLabelsRoute =
  AppOrgSlugWsSlugProjectsProjectIdSettingsLabelsRouteImport.update({
    id: '/settings/labels',
    path: '/settings/labels',
    getParentRoute: () => AppOrgSlugWsSlugProjectsProjectIdRoute,
  } as any)
const AppOrgSlugWsSlugProjectsProjectIdIssuesIssueIdRoute =
  AppOrgSlugWsSlugProjectsProjectIdIssuesIssueIdRouteImport.update({
    id: '/issues/$issueId',
    path: '/issues/$issueId',
    getParentRoute: () => AppOrgSlugWsSlugProjectsProjectIdRoute,
  } as any)
const AppOrgSlugWsSlugProjectsProjectIdCyclesCycleIdRoute =
  AppOrgSlugWsSlugProjectsProjectIdCyclesCycleIdRouteImport.update({
    id: '/cycles/$cycleId',
    path: '/cycles/$cycleId',
    getParentRoute: () => AppOrgSlugWsSlugProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orgs': typeof AppOrgsRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/register': typeof AuthRegisterRoute
  '/$orgSlug/$wsSlug': typeof AppOrgSlugWsSlugRouteWithChildren
  '/invite/$token': typeof AuthInviteTokenRoute
  '/$orgSlug/$wsSlug/': typeof AppOrgSlugWsSlugIndexRoute
  '/$orgSlug/$wsSlug/my/favorites': typeof AppOrgSlugWsSlugMyFavoritesRoute
  '/$orgSlug/$wsSlug/my/inbox': typeof AppOrgSlugWsSlugMyInboxRoute
  '/$orgSlug/$wsSlug/my/issues': typeof AppOrgSlugWsSlugMyIssuesRoute
  '/$orgSlug/$wsSlug/projects/$projectId': typeof AppOrgSlugWsSlugProjectsProjectIdRouteWithChildren
  '/$orgSlug/$wsSlug/settings/members': typeof AppOrgSlugWsSlugSettingsMembersRoute
  '/$orgSlug/$wsSlug/settings/profile': typeof AppOrgSlugWsSlugSettingsProfileRoute
  '/$orgSlug/$wsSlug/wiki/$spaceId': typeof AppOrgSlugWsSlugWikiSpaceIdRouteWithChildren
  '/$orgSlug/$wsSlug/projects/': typeof AppOrgSlugWsSlugProjectsIndexRoute
  '/$orgSlug/$wsSlug/settings/': typeof AppOrgSlugWsSlugSettingsIndexRoute
  '/$orgSlug/$wsSlug/wiki/': typeof AppOrgSlugWsSlugWikiIndexRoute
  '/$orgSlug/$wsSlug/settings/org/members': typeof AppOrgSlugWsSlugSettingsOrgMembersRoute
  '/$orgSlug/$wsSlug/wiki/$spaceId/$pageId': typeof AppOrgSlugWsSlugWikiSpaceIdPageIdRoute
  '/$orgSlug/$wsSlug/settings/org/': typeof AppOrgSlugWsSlugSettingsOrgIndexRoute
  '/$orgSlug/$wsSlug/projects/$projectId/cycles/$cycleId': typeof AppOrgSlugWsSlugProjectsProjectIdCyclesCycleIdRoute
  '/$orgSlug/$wsSlug/projects/$projectId/issues/$issueId': typeof AppOrgSlugWsSlugProjectsProjectIdIssuesIssueIdRoute
  '/$orgSlug/$wsSlug/projects/$projectId/settings/labels': typeof AppOrgSlugWsSlugProjectsProjectIdSettingsLabelsRoute
  '/$orgSlug/$wsSlug/projects/$projectId/settings/members': typeof AppOrgSlugWsSlugProjectsProjectIdSettingsMembersRoute
  '/$orgSlug/$wsSlug/projects/$projectId/views/$viewId': typeof AppOrgSlugWsSlugProjectsProjectIdViewsViewIdRoute
  '/$orgSlug/$wsSlug/projects/$projectId/board/': typeof AppOrgSlugWsSlugProjectsProjectIdBoardIndexRoute
  '/$orgSlug/$wsSlug/projects/$projectId/cycles/': typeof AppOrgSlugWsSlugProjectsProjectIdCyclesIndexRoute
  '/$orgSlug/$wsSlug/projects/$projectId/gantt/': typeof AppOrgSlugWsSlugProjectsProjectIdGanttIndexRoute
  '/$orgSlug/$wsSlug/projects/$projectId/issues/': typeof AppOrgSlugWsSlugProjectsProjectIdIssuesIndexRoute
  '/$orgSlug/$wsSlug/projects/$projectId/settings/': typeof AppOrgSlugWsSlugProjectsProjectIdSettingsIndexRoute
  '/$orgSlug/$wsSlug/projects/$projectId/wiki/': typeof AppOrgSlugWsSlugProjectsProjectIdWikiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orgs': typeof AppOrgsRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/register': typeof AuthRegisterRoute
  '/invite/$token': typeof AuthInviteTokenRoute
  '/$orgSlug/$wsSlug': typeof AppOrgSlugWsSlugIndexRoute
  '/$orgSlug/$wsSlug/my/favorites': typeof AppOrgSlugWsSlugMyFavoritesRoute
  '/$orgSlug/$wsSlug/my/inbox': typeof AppOrgSlugWsSlugMyInboxRoute
  '/$orgSlug/$wsSlug/my/issues': typeof AppOrgSlugWsSlugMyIssuesRoute
  '/$orgSlug/$wsSlug/projects/$projectId': typeof AppOrgSlugWsSlugProjectsProjectIdRouteWithChildren
  '/$orgSlug/$wsSlug/settings/members': typeof AppOrgSlugWsSlugSettingsMembersRoute
  '/$orgSlug/$wsSlug/settings/profile': typeof AppOrgSlugWsSlugSettingsProfileRoute
  '/$orgSlug/$wsSlug/wiki/$spaceId': typeof AppOrgSlugWsSlugWikiSpaceIdRouteWithChildren
  '/$orgSlug/$wsSlug/projects': typeof AppOrgSlugWsSlugProjectsIndexRoute
  '/$orgSlug/$wsSlug/settings': typeof AppOrgSlugWsSlugSettingsIndexRoute
  '/$orgSlug/$wsSlug/wiki': typeof AppOrgSlugWsSlugWikiIndexRoute
  '/$orgSlug/$wsSlug/settings/org/members': typeof AppOrgSlugWsSlugSettingsOrgMembersRoute
  '/$orgSlug/$wsSlug/wiki/$spaceId/$pageId': typeof AppOrgSlugWsSlugWikiSpaceIdPageIdRoute
  '/$orgSlug/$wsSlug/settings/org': typeof AppOrgSlugWsSlugSettingsOrgIndexRoute
  '/$orgSlug/$wsSlug/projects/$projectId/cycles/$cycleId': typeof AppOrgSlugWsSlugProjectsProjectIdCyclesCycleIdRoute
  '/$orgSlug/$wsSlug/projects/$projectId/issues/$issueId': typeof AppOrgSlugWsSlugProjectsProjectIdIssuesIssueIdRoute
  '/$orgSlug/$wsSlug/projects/$projectId/settings/labels': typeof AppOrgSlugWsSlugProjectsProjectIdSettingsLabelsRoute
  '/$orgSlug/$wsSlug/projects/$projectId/settings/members': typeof AppOrgSlugWsSlugProjectsProjectIdSettingsMembersRoute
  '/$orgSlug/$wsSlug/projects/$projectId/views/$viewId': typeof AppOrgSlugWsSlugProjectsProjectIdViewsViewIdRoute
  '/$orgSlug/$wsSlug/projects/$projectId/board': typeof AppOrgSlugWsSlugProjectsProjectIdBoardIndexRoute
  '/$orgSlug/$wsSlug/projects/$projectId/cycles': typeof AppOrgSlugWsSlugProjectsProjectIdCyclesIndexRoute
  '/$orgSlug/$wsSlug/projects/$projectId/gantt': typeof AppOrgSlugWsSlugProjectsProjectIdGanttIndexRoute
  '/$orgSlug/$wsSlug/projects/$projectId/issues': typeof AppOrgSlugWsSlugProjectsProjectIdIssuesIndexRoute
  '/$orgSlug/$wsSlug/projects/$projectId/settings': typeof AppOrgSlugWsSlugProjectsProjectIdSettingsIndexRoute
  '/$orgSlug/$wsSlug/projects/$projectId/wiki': typeof AppOrgSlugWsSlugProjectsProjectIdWikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/orgs': typeof AppOrgsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/$orgSlug/$wsSlug': typeof AppOrgSlugWsSlugRouteWithChildren
  '/_auth/invite/$token': typeof AuthInviteTokenRoute
  '/_app/$orgSlug/$wsSlug/': typeof AppOrgSlugWsSlugIndexRoute
  '/_app/$orgSlug/$wsSlug/my/favorites': typeof AppOrgSlugWsSlugMyFavoritesRoute
  '/_app/$orgSlug/$wsSlug/my/inbox': typeof AppOrgSlugWsSlugMyInboxRoute
  '/_app/$orgSlug/$wsSlug/my/issues': typeof AppOrgSlugWsSlugMyIssuesRoute
  '/_app/$orgSlug/$wsSlug/projects/$projectId': typeof AppOrgSlugWsSlugProjectsProjectIdRouteWithChildren
  '/_app/$orgSlug/$wsSlug/settings/members': typeof AppOrgSlugWsSlugSettingsMembersRoute
  '/_app/$orgSlug/$wsSlug/settings/profile': typeof AppOrgSlugWsSlugSettingsProfileRoute
  '/_app/$orgSlug/$wsSlug/wiki/$spaceId': typeof AppOrgSlugWsSlugWikiSpaceIdRouteWithChildren
  '/_app/$orgSlug/$wsSlug/projects/': typeof AppOrgSlugWsSlugProjectsIndexRoute
  '/_app/$orgSlug/$wsSlug/settings/': typeof AppOrgSlugWsSlugSettingsIndexRoute
  '/_app/$orgSlug/$wsSlug/wiki/': typeof AppOrgSlugWsSlugWikiIndexRoute
  '/_app/$orgSlug/$wsSlug/settings/org/members': typeof AppOrgSlugWsSlugSettingsOrgMembersRoute
  '/_app/$orgSlug/$wsSlug/wiki/$spaceId/$pageId': typeof AppOrgSlugWsSlugWikiSpaceIdPageIdRoute
  '/_app/$orgSlug/$wsSlug/settings/org/': typeof AppOrgSlugWsSlugSettingsOrgIndexRoute
  '/_app/$orgSlug/$wsSlug/projects/$projectId/cycles/$cycleId': typeof AppOrgSlugWsSlugProjectsProjectIdCyclesCycleIdRoute
  '/_app/$orgSlug/$wsSlug/projects/$projectId/issues/$issueId': typeof AppOrgSlugWsSlugProjectsProjectIdIssuesIssueIdRoute
  '/_app/$orgSlug/$wsSlug/projects/$projectId/settings/labels': typeof AppOrgSlugWsSlugProjectsProjectIdSettingsLabelsRoute
  '/_app/$orgSlug/$wsSlug/projects/$projectId/settings/members': typeof AppOrgSlugWsSlugProjectsProjectIdSettingsMembersRoute
  '/_app/$orgSlug/$wsSlug/projects/$projectId/views/$viewId': typeof AppOrgSlugWsSlugProjectsProjectIdViewsViewIdRoute
  '/_app/$orgSlug/$wsSlug/projects/$projectId/board/': typeof AppOrgSlugWsSlugProjectsProjectIdBoardIndexRoute
  '/_app/$orgSlug/$wsSlug/projects/$projectId/cycles/': typeof AppOrgSlugWsSlugProjectsProjectIdCyclesIndexRoute
  '/_app/$orgSlug/$wsSlug/projects/$projectId/gantt/': typeof AppOrgSlugWsSlugProjectsProjectIdGanttIndexRoute
  '/_app/$orgSlug/$wsSlug/projects/$projectId/issues/': typeof AppOrgSlugWsSlugProjectsProjectIdIssuesIndexRoute
  '/_app/$orgSlug/$wsSlug/projects/$projectId/settings/': typeof AppOrgSlugWsSlugProjectsProjectIdSettingsIndexRoute
  '/_app/$orgSlug/$wsSlug/projects/$projectId/wiki/': typeof AppOrgSlugWsSlugProjectsProjectIdWikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/orgs'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/$orgSlug/$wsSlug'
    | '/invite/$token'
    | '/$orgSlug/$wsSlug/'
    | '/$orgSlug/$wsSlug/my/favorites'
    | '/$orgSlug/$wsSlug/my/inbox'
    | '/$orgSlug/$wsSlug/my/issues'
    | '/$orgSlug/$wsSlug/projects/$projectId'
    | '/$orgSlug/$wsSlug/settings/members'
    | '/$orgSlug/$wsSlug/settings/profile'
    | '/$orgSlug/$wsSlug/wiki/$spaceId'
    | '/$orgSlug/$wsSlug/projects/'
    | '/$orgSlug/$wsSlug/settings/'
    | '/$orgSlug/$wsSlug/wiki/'
    | '/$orgSlug/$wsSlug/settings/org/members'
    | '/$orgSlug/$wsSlug/wiki/$spaceId/$pageId'
    | '/$orgSlug/$wsSlug/settings/org/'
    | '/$orgSlug/$wsSlug/projects/$projectId/cycles/$cycleId'
    | '/$orgSlug/$wsSlug/projects/$projectId/issues/$issueId'
    | '/$orgSlug/$wsSlug/projects/$projectId/settings/labels'
    | '/$orgSlug/$wsSlug/projects/$projectId/settings/members'
    | '/$orgSlug/$wsSlug/projects/$projectId/views/$viewId'
    | '/$orgSlug/$wsSlug/projects/$projectId/board/'
    | '/$orgSlug/$wsSlug/projects/$projectId/cycles/'
    | '/$orgSlug/$wsSlug/projects/$projectId/gantt/'
    | '/$orgSlug/$wsSlug/projects/$projectId/issues/'
    | '/$orgSlug/$wsSlug/projects/$projectId/settings/'
    | '/$orgSlug/$wsSlug/projects/$projectId/wiki/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/orgs'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/invite/$token'
    | '/$orgSlug/$wsSlug'
    | '/$orgSlug/$wsSlug/my/favorites'
    | '/$orgSlug/$wsSlug/my/inbox'
    | '/$orgSlug/$wsSlug/my/issues'
    | '/$orgSlug/$wsSlug/projects/$projectId'
    | '/$orgSlug/$wsSlug/settings/members'
    | '/$orgSlug/$wsSlug/settings/profile'
    | '/$orgSlug/$wsSlug/wiki/$spaceId'
    | '/$orgSlug/$wsSlug/projects'
    | '/$orgSlug/$wsSlug/settings'
    | '/$orgSlug/$wsSlug/wiki'
    | '/$orgSlug/$wsSlug/settings/org/members'
    | '/$orgSlug/$wsSlug/wiki/$spaceId/$pageId'
    | '/$orgSlug/$wsSlug/settings/org'
    | '/$orgSlug/$wsSlug/projects/$projectId/cycles/$cycleId'
    | '/$orgSlug/$wsSlug/projects/$projectId/issues/$issueId'
    | '/$orgSlug/$wsSlug/projects/$projectId/settings/labels'
    | '/$orgSlug/$wsSlug/projects/$projectId/settings/members'
    | '/$orgSlug/$wsSlug/projects/$projectId/views/$viewId'
    | '/$orgSlug/$wsSlug/projects/$projectId/board'
    | '/$orgSlug/$wsSlug/projects/$projectId/cycles'
    | '/$orgSlug/$wsSlug/projects/$projectId/gantt'
    | '/$orgSlug/$wsSlug/projects/$projectId/issues'
    | '/$orgSlug/$wsSlug/projects/$projectId/settings'
    | '/$orgSlug/$wsSlug/projects/$projectId/wiki'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/orgs'
    | '/_auth/login'
    | '/_auth/onboarding'
    | '/_auth/register'
    | '/_app/$orgSlug/$wsSlug'
    | '/_auth/invite/$token'
    | '/_app/$orgSlug/$wsSlug/'
    | '/_app/$orgSlug/$wsSlug/my/favorites'
    | '/_app/$orgSlug/$wsSlug/my/inbox'
    | '/_app/$orgSlug/$wsSlug/my/issues'
    | '/_app/$orgSlug/$wsSlug/projects/$projectId'
    | '/_app/$orgSlug/$wsSlug/settings/members'
    | '/_app/$orgSlug/$wsSlug/settings/profile'
    | '/_app/$orgSlug/$wsSlug/wiki/$spaceId'
    | '/_app/$orgSlug/$wsSlug/projects/'
    | '/_app/$orgSlug/$wsSlug/settings/'
    | '/_app/$orgSlug/$wsSlug/wiki/'
    | '/_app/$orgSlug/$wsSlug/settings/org/members'
    | '/_app/$orgSlug/$wsSlug/wiki/$spaceId/$pageId'
    | '/_app/$orgSlug/$wsSlug/settings/org/'
    | '/_app/$orgSlug/$wsSlug/projects/$projectId/cycles/$cycleId'
    | '/_app/$orgSlug/$wsSlug/projects/$projectId/issues/$issueId'
    | '/_app/$orgSlug/$wsSlug/projects/$projectId/settings/labels'
    | '/_app/$orgSlug/$wsSlug/projects/$projectId/settings/members'
    | '/_app/$orgSlug/$wsSlug/projects/$projectId/views/$viewId'
    | '/_app/$orgSlug/$wsSlug/projects/$projectId/board/'
    | '/_app/$orgSlug/$wsSlug/projects/$projectId/cycles/'
    | '/_app/$orgSlug/$wsSlug/projects/$projectId/gantt/'
    | '/_app/$orgSlug/$wsSlug/projects/$projectId/issues/'
    | '/_app/$orgSlug/$wsSlug/projects/$projectId/settings/'
    | '/_app/$orgSlug/$wsSlug/projects/$projectId/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/orgs': {
      id: '/_app/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AppOrgsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/invite/$token': {
      id: '/_auth/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthInviteTokenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/$orgSlug/$wsSlug': {
      id: '/_app/$orgSlug/$wsSlug'
      path: '/$orgSlug/$wsSlug'
      fullPath: '/$orgSlug/$wsSlug'
      preLoaderRoute: typeof AppOrgSlugWsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$orgSlug/$wsSlug/': {
      id: '/_app/$orgSlug/$wsSlug/'
      path: '/'
      fullPath: '/$orgSlug/$wsSlug/'
      preLoaderRoute: typeof AppOrgSlugWsSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugWsSlugRoute
    }
    '/_app/$orgSlug/$wsSlug/wiki/': {
      id: '/_app/$orgSlug/$wsSlug/wiki/'
      path: '/wiki'
      fullPath: '/$orgSlug/$wsSlug/wiki/'
      preLoaderRoute: typeof AppOrgSlugWsSlugWikiIndexRouteImport
      parentRoute: typeof AppOrgSlugWsSlugRoute
    }
    '/_app/$orgSlug/$wsSlug/settings/': {
      id: '/_app/$orgSlug/$wsSlug/settings/'
      path: '/settings'
      fullPath: '/$orgSlug/$wsSlug/settings/'
      preLoaderRoute: typeof AppOrgSlugWsSlugSettingsIndexRouteImport
      parentRoute: typeof AppOrgSlugWsSlugRoute
    }
    '/_app/$orgSlug/$wsSlug/projects/': {
      id: '/_app/$orgSlug/$wsSlug/projects/'
      path: '/projects'
      fullPath: '/$orgSlug/$wsSlug/projects/'
      preLoaderRoute: typeof AppOrgSlugWsSlugProjectsIndexRouteImport
      parentRoute: typeof AppOrgSlugWsSlugRoute
    }
    '/_app/$orgSlug/$wsSlug/wiki/$spaceId': {
      id: '/_app/$orgSlug/$wsSlug/wiki/$spaceId'
      path: '/wiki/$spaceId'
      fullPath: '/$orgSlug/$wsSlug/wiki/$spaceId'
      preLoaderRoute: typeof AppOrgSlugWsSlugWikiSpaceIdRouteImport
      parentRoute: typeof AppOrgSlugWsSlugRoute
    }
    '/_app/$orgSlug/$wsSlug/settings/profile': {
      id: '/_app/$orgSlug/$wsSlug/settings/profile'
      path: '/settings/profile'
      fullPath: '/$orgSlug/$wsSlug/settings/profile'
      preLoaderRoute: typeof AppOrgSlugWsSlugSettingsProfileRouteImport
      parentRoute: typeof AppOrgSlugWsSlugRoute
    }
    '/_app/$orgSlug/$wsSlug/settings/members': {
      id: '/_app/$orgSlug/$wsSlug/settings/members'
      path: '/settings/members'
      fullPath: '/$orgSlug/$wsSlug/settings/members'
      preLoaderRoute: typeof AppOrgSlugWsSlugSettingsMembersRouteImport
      parentRoute: typeof AppOrgSlugWsSlugRoute
    }
    '/_app/$orgSlug/$wsSlug/projects/$projectId': {
      id: '/_app/$orgSlug/$wsSlug/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/$orgSlug/$wsSlug/projects/$projectId'
      preLoaderRoute: typeof AppOrgSlugWsSlugProjectsProjectIdRouteImport
      parentRoute: typeof AppOrgSlugWsSlugRoute
    }
    '/_app/$orgSlug/$wsSlug/my/issues': {
      id: '/_app/$orgSlug/$wsSlug/my/issues'
      path: '/my/issues'
      fullPath: '/$orgSlug/$wsSlug/my/issues'
      preLoaderRoute: typeof AppOrgSlugWsSlugMyIssuesRouteImport
      parentRoute: typeof AppOrgSlugWsSlugRoute
    }
    '/_app/$orgSlug/$wsSlug/my/inbox': {
      id: '/_app/$orgSlug/$wsSlug/my/inbox'
      path: '/my/inbox'
      fullPath: '/$orgSlug/$wsSlug/my/inbox'
      preLoaderRoute: typeof AppOrgSlugWsSlugMyInboxRouteImport
      parentRoute: typeof AppOrgSlugWsSlugRoute
    }
    '/_app/$orgSlug/$wsSlug/my/favorites': {
      id: '/_app/$orgSlug/$wsSlug/my/favorites'
      path: '/my/favorites'
      fullPath: '/$orgSlug/$wsSlug/my/favorites'
      preLoaderRoute: typeof AppOrgSlugWsSlugMyFavoritesRouteImport
      parentRoute: typeof AppOrgSlugWsSlugRoute
    }
    '/_app/$orgSlug/$wsSlug/settings/org/': {
      id: '/_app/$orgSlug/$wsSlug/settings/org/'
      path: '/settings/org'
      fullPath: '/$orgSlug/$wsSlug/settings/org/'
      preLoaderRoute: typeof AppOrgSlugWsSlugSettingsOrgIndexRouteImport
      parentRoute: typeof AppOrgSlugWsSlugRoute
    }
    '/_app/$orgSlug/$wsSlug/wiki/$spaceId/$pageId': {
      id: '/_app/$orgSlug/$wsSlug/wiki/$spaceId/$pageId'
      path: '/$pageId'
      fullPath: '/$orgSlug/$wsSlug/wiki/$spaceId/$pageId'
      preLoaderRoute: typeof AppOrgSlugWsSlugWikiSpaceIdPageIdRouteImport
      parentRoute: typeof AppOrgSlugWsSlugWikiSpaceIdRoute
    }
    '/_app/$orgSlug/$wsSlug/settings/org/members': {
      id: '/_app/$orgSlug/$wsSlug/settings/org/members'
      path: '/settings/org/members'
      fullPath: '/$orgSlug/$wsSlug/settings/org/members'
      preLoaderRoute: typeof AppOrgSlugWsSlugSettingsOrgMembersRouteImport
      parentRoute: typeof AppOrgSlugWsSlugRoute
    }
    '/_app/$orgSlug/$wsSlug/projects/$projectId/wiki/': {
      id: '/_app/$orgSlug/$wsSlug/projects/$projectId/wiki/'
      path: '/wiki'
      fullPath: '/$orgSlug/$wsSlug/projects/$projectId/wiki/'
      preLoaderRoute: typeof AppOrgSlugWsSlugProjectsProjectIdWikiIndexRouteImport
      parentRoute: typeof AppOrgSlugWsSlugProjectsProjectIdRoute
    }
    '/_app/$orgSlug/$wsSlug/projects/$projectId/settings/': {
      id: '/_app/$orgSlug/$wsSlug/projects/$projectId/settings/'
      path: '/settings'
      fullPath: '/$orgSlug/$wsSlug/projects/$projectId/settings/'
      preLoaderRoute: typeof AppOrgSlugWsSlugProjectsProjectIdSettingsIndexRouteImport
      parentRoute: typeof AppOrgSlugWsSlugProjectsProjectIdRoute
    }
    '/_app/$orgSlug/$wsSlug/projects/$projectId/issues/': {
      id: '/_app/$orgSlug/$wsSlug/projects/$projectId/issues/'
      path: '/issues'
      fullPath: '/$orgSlug/$wsSlug/projects/$projectId/issues/'
      preLoaderRoute: typeof AppOrgSlugWsSlugProjectsProjectIdIssuesIndexRouteImport
      parentRoute: typeof AppOrgSlugWsSlugProjectsProjectIdRoute
    }
    '/_app/$orgSlug/$wsSlug/projects/$projectId/gantt/': {
      id: '/_app/$orgSlug/$wsSlug/projects/$projectId/gantt/'
      path: '/gantt'
      fullPath: '/$orgSlug/$wsSlug/projects/$projectId/gantt/'
      preLoaderRoute: typeof AppOrgSlugWsSlugProjectsProjectIdGanttIndexRouteImport
      parentRoute: typeof AppOrgSlugWsSlugProjectsProjectIdRoute
    }
    '/_app/$orgSlug/$wsSlug/projects/$projectId/cycles/': {
      id: '/_app/$orgSlug/$wsSlug/projects/$projectId/cycles/'
      path: '/cycles'
      fullPath: '/$orgSlug/$wsSlug/projects/$projectId/cycles/'
      preLoaderRoute: typeof AppOrgSlugWsSlugProjectsProjectIdCyclesIndexRouteImport
      parentRoute: typeof AppOrgSlugWsSlugProjectsProjectIdRoute
    }
    '/_app/$orgSlug/$wsSlug/projects/$projectId/board/': {
      id: '/_app/$orgSlug/$wsSlug/projects/$projectId/board/'
      path: '/board'
      fullPath: '/$orgSlug/$wsSlug/projects/$projectId/board/'
      preLoaderRoute: typeof AppOrgSlugWsSlugProjectsProjectIdBoardIndexRouteImport
      parentRoute: typeof AppOrgSlugWsSlugProjectsProjectIdRoute
    }
    '/_app/$orgSlug/$wsSlug/projects/$projectId/views/$viewId': {
      id: '/_app/$orgSlug/$wsSlug/projects/$projectId/views/$viewId'
      path: '/views/$viewId'
      fullPath: '/$orgSlug/$wsSlug/projects/$projectId/views/$viewId'
      preLoaderRoute: typeof AppOrgSlugWsSlugProjectsProjectIdViewsViewIdRouteImport
      parentRoute: typeof AppOrgSlugWsSlugProjectsProjectIdRoute
    }
    '/_app/$orgSlug/$wsSlug/projects/$projectId/settings/members': {
      id: '/_app/$orgSlug/$wsSlug/projects/$projectId/settings/members'
      path: '/settings/members'
      fullPath: '/$orgSlug/$wsSlug/projects/$projectId/settings/members'
      preLoaderRoute: typeof AppOrgSlugWsSlugProjectsProjectIdSettingsMembersRouteImport
      parentRoute: typeof AppOrgSlugWsSlugProjectsProjectIdRoute
    }
    '/_app/$orgSlug/$wsSlug/projects/$projectId/settings/labels': {
      id: '/_app/$orgSlug/$wsSlug/projects/$projectId/settings/labels'
      path: '/settings/labels'
      fullPath: '/$orgSlug/$wsSlug/projects/$projectId/settings/labels'
      preLoaderRoute: typeof AppOrgSlugWsSlugProjectsProjectIdSettingsLabelsRouteImport
      parentRoute: typeof AppOrgSlugWsSlugProjectsProjectIdRoute
    }
    '/_app/$orgSlug/$wsSlug/projects/$projectId/issues/$issueId': {
      id: '/_app/$orgSlug/$wsSlug/projects/$projectId/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/$orgSlug/$wsSlug/projects/$projectId/issues/$issueId'
      preLoaderRoute: typeof AppOrgSlugWsSlugProjectsProjectIdIssuesIssueIdRouteImport
      parentRoute: typeof AppOrgSlugWsSlugProjectsProjectIdRoute
    }
    '/_app/$orgSlug/$wsSlug/projects/$projectId/cycles/$cycleId': {
      id: '/_app/$orgSlug/$wsSlug/projects/$projectId/cycles/$cycleId'
      path: '/cycles/$cycleId'
      fullPath: '/$orgSlug/$wsSlug/projects/$projectId/cycles/$cycleId'
      preLoaderRoute: typeof AppOrgSlugWsSlugProjectsProjectIdCyclesCycleIdRouteImport
      parentRoute: typeof AppOrgSlugWsSlugProjectsProjectIdRoute
    }
  }
}

interface AppOrgSlugWsSlugProjectsProjectIdRouteChildren {
  AppOrgSlugWsSlugProjectsProjectIdCyclesCycleIdRoute: typeof AppOrgSlugWsSlugProjectsProjectIdCyclesCycleIdRoute
  AppOrgSlugWsSlugProjectsProjectIdIssuesIssueIdRoute: typeof AppOrgSlugWsSlugProjectsProjectIdIssuesIssueIdRoute
  AppOrgSlugWsSlugProjectsProjectIdSettingsLabelsRoute: typeof AppOrgSlugWsSlugProjectsProjectIdSettingsLabelsRoute
  AppOrgSlugWsSlugProjectsProjectIdSettingsMembersRoute: typeof AppOrgSlugWsSlugProjectsProjectIdSettingsMembersRoute
  AppOrgSlugWsSlugProjectsProjectIdViewsViewIdRoute: typeof AppOrgSlugWsSlugProjectsProjectIdViewsViewIdRoute
  AppOrgSlugWsSlugProjectsProjectIdBoardIndexRoute: typeof AppOrgSlugWsSlugProjectsProjectIdBoardIndexRoute
  AppOrgSlugWsSlugProjectsProjectIdCyclesIndexRoute: typeof AppOrgSlugWsSlugProjectsProjectIdCyclesIndexRoute
  AppOrgSlugWsSlugProjectsProjectIdGanttIndexRoute: typeof AppOrgSlugWsSlugProjectsProjectIdGanttIndexRoute
  AppOrgSlugWsSlugProjectsProjectIdIssuesIndexRoute: typeof AppOrgSlugWsSlugProjectsProjectIdIssuesIndexRoute
  AppOrgSlugWsSlugProjectsProjectIdSettingsIndexRoute: typeof AppOrgSlugWsSlugProjectsProjectIdSettingsIndexRoute
  AppOrgSlugWsSlugProjectsProjectIdWikiIndexRoute: typeof AppOrgSlugWsSlugProjectsProjectIdWikiIndexRoute
}

const AppOrgSlugWsSlugProjectsProjectIdRouteChildren: AppOrgSlugWsSlugProjectsProjectIdRouteChildren =
  {
    AppOrgSlugWsSlugProjectsProjectIdCyclesCycleIdRoute:
      AppOrgSlugWsSlugProjectsProjectIdCyclesCycleIdRoute,
    AppOrgSlugWsSlugProjectsProjectIdIssuesIssueIdRoute:
      AppOrgSlugWsSlugProjectsProjectIdIssuesIssueIdRoute,
    AppOrgSlugWsSlugProjectsProjectIdSettingsLabelsRoute:
      AppOrgSlugWsSlugProjectsProjectIdSettingsLabelsRoute,
    AppOrgSlugWsSlugProjectsProjectIdSettingsMembersRoute:
      AppOrgSlugWsSlugProjectsProjectIdSettingsMembersRoute,
    AppOrgSlugWsSlugProjectsProjectIdViewsViewIdRoute:
      AppOrgSlugWsSlugProjectsProjectIdViewsViewIdRoute,
    AppOrgSlugWsSlugProjectsProjectIdBoardIndexRoute:
      AppOrgSlugWsSlugProjectsProjectIdBoardIndexRoute,
    AppOrgSlugWsSlugProjectsProjectIdCyclesIndexRoute:
      AppOrgSlugWsSlugProjectsProjectIdCyclesIndexRoute,
    AppOrgSlugWsSlugProjectsProjectIdGanttIndexRoute:
      AppOrgSlugWsSlugProjectsProjectIdGanttIndexRoute,
    AppOrgSlugWsSlugProjectsProjectIdIssuesIndexRoute:
      AppOrgSlugWsSlugProjectsProjectIdIssuesIndexRoute,
    AppOrgSlugWsSlugProjectsProjectIdSettingsIndexRoute:
      AppOrgSlugWsSlugProjectsProjectIdSettingsIndexRoute,
    AppOrgSlugWsSlugProjectsProjectIdWikiIndexRoute:
      AppOrgSlugWsSlugProjectsProjectIdWikiIndexRoute,
  }

const AppOrgSlugWsSlugProjectsProjectIdRouteWithChildren =
  AppOrgSlugWsSlugProjectsProjectIdRoute._addFileChildren(
    AppOrgSlugWsSlugProjectsProjectIdRouteChildren,
  )

interface AppOrgSlugWsSlugWikiSpaceIdRouteChildren {
  AppOrgSlugWsSlugWikiSpaceIdPageIdRoute: typeof AppOrgSlugWsSlugWikiSpaceIdPageIdRoute
}

const AppOrgSlugWsSlugWikiSpaceIdRouteChildren: AppOrgSlugWsSlugWikiSpaceIdRouteChildren =
  {
    AppOrgSlugWsSlugWikiSpaceIdPageIdRoute:
      AppOrgSlugWsSlugWikiSpaceIdPageIdRoute,
  }

const AppOrgSlugWsSlugWikiSpaceIdRouteWithChildren =
  AppOrgSlugWsSlugWikiSpaceIdRoute._addFileChildren(
    AppOrgSlugWsSlugWikiSpaceIdRouteChildren,
  )

interface AppOrgSlugWsSlugRouteChildren {
  AppOrgSlugWsSlugIndexRoute: typeof AppOrgSlugWsSlugIndexRoute
  AppOrgSlugWsSlugMyFavoritesRoute: typeof AppOrgSlugWsSlugMyFavoritesRoute
  AppOrgSlugWsSlugMyInboxRoute: typeof AppOrgSlugWsSlugMyInboxRoute
  AppOrgSlugWsSlugMyIssuesRoute: typeof AppOrgSlugWsSlugMyIssuesRoute
  AppOrgSlugWsSlugProjectsProjectIdRoute: typeof AppOrgSlugWsSlugProjectsProjectIdRouteWithChildren
  AppOrgSlugWsSlugSettingsMembersRoute: typeof AppOrgSlugWsSlugSettingsMembersRoute
  AppOrgSlugWsSlugSettingsProfileRoute: typeof AppOrgSlugWsSlugSettingsProfileRoute
  AppOrgSlugWsSlugWikiSpaceIdRoute: typeof AppOrgSlugWsSlugWikiSpaceIdRouteWithChildren
  AppOrgSlugWsSlugProjectsIndexRoute: typeof AppOrgSlugWsSlugProjectsIndexRoute
  AppOrgSlugWsSlugSettingsIndexRoute: typeof AppOrgSlugWsSlugSettingsIndexRoute
  AppOrgSlugWsSlugWikiIndexRoute: typeof AppOrgSlugWsSlugWikiIndexRoute
  AppOrgSlugWsSlugSettingsOrgMembersRoute: typeof AppOrgSlugWsSlugSettingsOrgMembersRoute
  AppOrgSlugWsSlugSettingsOrgIndexRoute: typeof AppOrgSlugWsSlugSettingsOrgIndexRoute
}

const AppOrgSlugWsSlugRouteChildren: AppOrgSlugWsSlugRouteChildren = {
  AppOrgSlugWsSlugIndexRoute: AppOrgSlugWsSlugIndexRoute,
  AppOrgSlugWsSlugMyFavoritesRoute: AppOrgSlugWsSlugMyFavoritesRoute,
  AppOrgSlugWsSlugMyInboxRoute: AppOrgSlugWsSlugMyInboxRoute,
  AppOrgSlugWsSlugMyIssuesRoute: AppOrgSlugWsSlugMyIssuesRoute,
  AppOrgSlugWsSlugProjectsProjectIdRoute:
    AppOrgSlugWsSlugProjectsProjectIdRouteWithChildren,
  AppOrgSlugWsSlugSettingsMembersRoute: AppOrgSlugWsSlugSettingsMembersRoute,
  AppOrgSlugWsSlugSettingsProfileRoute: AppOrgSlugWsSlugSettingsProfileRoute,
  AppOrgSlugWsSlugWikiSpaceIdRoute:
    AppOrgSlugWsSlugWikiSpaceIdRouteWithChildren,
  AppOrgSlugWsSlugProjectsIndexRoute: AppOrgSlugWsSlugProjectsIndexRoute,
  AppOrgSlugWsSlugSettingsIndexRoute: AppOrgSlugWsSlugSettingsIndexRoute,
  AppOrgSlugWsSlugWikiIndexRoute: AppOrgSlugWsSlugWikiIndexRoute,
  AppOrgSlugWsSlugSettingsOrgMembersRoute:
    AppOrgSlugWsSlugSettingsOrgMembersRoute,
  AppOrgSlugWsSlugSettingsOrgIndexRoute: AppOrgSlugWsSlugSettingsOrgIndexRoute,
}

const AppOrgSlugWsSlugRouteWithChildren =
  AppOrgSlugWsSlugRoute._addFileChildren(AppOrgSlugWsSlugRouteChildren)

interface AppRouteChildren {
  AppOrgsRoute: typeof AppOrgsRoute
  AppOrgSlugWsSlugRoute: typeof AppOrgSlugWsSlugRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppOrgsRoute: AppOrgsRoute,
  AppOrgSlugWsSlugRoute: AppOrgSlugWsSlugRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthInviteTokenRoute: typeof AuthInviteTokenRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthInviteTokenRoute: AuthInviteTokenRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
