apiVersion: v2
name: worknest
description: A Helm chart for Worknest - open-source & local-first collaboration workspace
type: application
version: 0.2.2
# appVersion is auto-updated by the release workflow
appVersion: '1.0.0'

dependencies:
  - name: postgresql
    version: '16.7.4'
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
  - name: valkey
    version: '5.1.0'
    repository: 'https://charts.bitnami.com/bitnami'
    alias: redis
    condition: redis.enabled
  - name: minio
    version: '16.0.10'
    repository: 'https://charts.bitnami.com/bitnami'
    condition: minio.enabled
